workflows:
  build-react-app:
    name: Build React App
    environment:
      node: v22.14.0   
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build the project
        script: npm run build
    artifacts:
      - build/**